apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rwop
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOncePod  
  hostPath:
    path: /mnt/data/rwm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual