apiVersion: v1
kind: Service
metadata:
  name: app-deploy-service
  namespace: app-service
spec:
  selector:
    app: app-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP